@Netflix.API_HostAddress = http://localhost:5267

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYWExOGMwNy0xNzNiLTRkNjctYjA4Ny05ODU3ZjA3YTVjNGUiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiI1YTE5NTY3Yi0yNDhlLTQyMDctYjYxOC00M2UyZjRlZjFiNWUiLCJleHAiOjE3MjM4MTg1NzMsImlzcyI6IkxvY2FsaG9zdE5ldGZsaXgiLCJhdWQiOiJMb2NhbGhvc3ROZXRmbGl4In0.xgx0Vsjrc8aLghJdFQaYpnP8PoW1k6fAi-rNKnvKGYo

GET http://localhost:5267/api/film/getall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiIyMTllODVmYi01MDczLTQ3MTAtOWM1NS00MzEyMzUzNDcyYjQiLCJleHAiOjE3MjM3NDA0ODksImlzcyI6IkxvY2FsaG9zdE5ldGZsaXgiLCJhdWQiOiJMb2NhbGhvc3ROZXRmbGl4In0.OSLFc-0-yLFmEGyWih4JnipM9W153hVFTq47gjjB6Es



